# Generated by Django 4.2 on 2023-05-10 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0003_userprofile_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shopping_Cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliar_Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_n', models.CharField(max_length=13)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('on_process', 'on_procces')], max_length=20)),
                ('addres', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.userinformation')),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shopping_Cart.shopping_cart')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
