# Generated by Django 4.2 on 2023-04-21 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Pictutes')),
                ('category', models.CharField(choices=[('Digital_Product', 'Digital_Product'), ('Household_appliances', 'Household_appliances'), ('Educational', 'Educational')], max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(null=True, unique=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('created_data', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Digital_Product',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.baseitem')),
                ('color', models.CharField(choices=[('black', 'black'), ('white', 'white'), ('silver', 'silver'), ('blue', 'blue'), ('red', 'red'), ('green', 'green'), ('yellow', 'yellow')], max_length=120, null=True)),
                ('volume', models.SmallIntegerField(default=0, null=True)),
            ],
            bases=('product.baseitem',),
        ),
        migrations.CreateModel(
            name='Educational',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.baseitem')),
                ('recommended_age', models.CharField(max_length=150)),
            ],
            bases=('product.baseitem',),
        ),
        migrations.CreateModel(
            name='Household_appliances',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.baseitem')),
                ('color', models.CharField(choices=[('black', 'black'), ('white', 'white'), ('silver', 'silver'), ('blue', 'blue'), ('red', 'red'), ('green', 'green'), ('yellow', 'yellow')], max_length=100)),
            ],
            bases=('product.baseitem',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('educational_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.educational')),
                ('language', models.CharField(choices=[('russian', 'Russian'), ('english', 'English')], max_length=40)),
                ('author', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=250)),
            ],
            bases=('product.educational',),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('digital_product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.digital_product')),
                ('screen_size', models.CharField(max_length=100)),
                ('touch_screen_display', models.BooleanField()),
                ('graphics_card', models.BooleanField()),
            ],
            bases=('product.digital_product',),
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('digital_product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.digital_product')),
                ('type_choice', models.CharField(choices=[('redmi', 'Redmi'), ('samsung', 'Samsung'), ('apple', 'Apple'), ('nokia', 'Nokia'), ('vivo', 'Vivo')], max_length=50)),
            ],
            bases=('product.digital_product',),
        ),
        migrations.CreateModel(
            name='Stationery',
            fields=[
                ('educational_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.educational')),
            ],
            bases=('product.educational',),
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('household_appliances_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.household_appliances')),
                ('decision', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=20)),
            ],
            bases=('product.household_appliances',),
        ),
    ]
