# Generated by Django 4.2 on 2023-05-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='touch_screen_display',
        ),
        migrations.RemoveField(
            model_name='digital_product',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='television',
            name='decision',
        ),
    ]
