# Generated by Django 4.2.1 on 2023-06-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_computer_touch_screen_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('russian', 'Russian'), ('english', 'English'), ('uzbek', 'Uzbek')], max_length=40),
        ),
    ]
